README.md, fastapi_sqla/__init__.py, tests/test_middleware.py, tests/test_pagination.py
* Simplify getting an SQLAlchemy session & pagination utilities (inspired from https://github.com/uriyyo/fastapi-pagination);
* Document getting an SQLAlchemy session using FastAPI dependency injection or using the context manager;
* Removed `with_session`: directly use `fastapi_sqla.Session` instead;
* Renamed:
- `with_pagination` to `Paginate`
- `Paginated` to `Page`
* Removed `PaginatedResult` as only `Paginate` is sufficient;
=> refactor: Simplify API

.circleci/config.yml, poetry.lock, pyproject.toml, setup.cfg, tests/conftest.py, tests/test_middleware.py, tests/test_pagination.py
* Former CI config was actually running tests against the sqlalchemy version installed by poetry;
* Changed it so that dependencies are installed by tox using `pyproject.toml`: this is the standard way IIUC;
* Today I learnt by reading on python-poetry/poetry#1941 that `[dev.dependencies]` section is not standard/compliant with [pep-517](https://www.python.org/dev/peps/pep-0517/);
* It is a `chore` as it doesn't fix anything in the library
* blocking #28
=> chore: fix tox configuration

.circleci/config.yml, README.md, fastapi_sqla/__init__.py, fastapi_sqla/_pytest_plugin.py, tests/test_pagination.py
* Pagination now allows 2.0 sqla queries.
Blocked by 
* #27
=> feat: port to SQLAlchemy 1.4 / 2.0

.circleci/config.yml, fastapi_sqla/_pytest_plugin.py, pyproject.toml, tests/conftest.py, tests/test_asyncio_support.py, tests/test_middleware.py, tests/test_pagination.py, tests/test_pytest_plugin.py
As described in #34, `asynpg` is required when using pytest fixtures.
=> fix: fixtures must not require asyncpg

.gitignore, README.md, fastapi_sqla/__init__.py, setup.cfg, tests/test_pagination.py
* Custom pagination relying on a callable rather than a FastAPI dependency is sub-optimal;
* This PR introduces a breaking change to change that callable to be a dependency;
=> feat: use query_count as a FastAPI dependency

fastapi_sqla/__init__.py, fastapi_sqla/_pytest_plugin.py, fastapi_sqla/asyncio_support.py, tests/test_asyncio_support.py, tests/test_startup.py
* fastapi-sqla does not obviously fail at startup if badly configured: Fail early, fail fast by querying db at startup using the sqla sessions configured.
* [DIA-38713]
[DIA-38713]: https://dialoguemd.atlassian.net/browse/DIA-38713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: fail at startup when connections info is incorrect - DIA-38713

fastapi_sqla/__init__.py, tests/test_pagination.py
* When a non-scalar query has a JSON column, pagination fails:
```
sqlalchemy.exc.InvalidRequestError: 
Can't apply uniqueness to row tuple containing value of type JSON(); 
this datatype produces non-hashable values
```
* [Example of failure](https://app.circleci.com/pipelines/github/dialoguemd/fastapi-sqla/436/workflows/3712f9fb-e79e-4413-933b-65ecfe16797e)
* [DIA-40003]
[DIA-40003]: https://dialoguemd.atlassian.net/browse/DIA-40003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: pagination fail non scalar JSON results - DIA-40003

fastapi_sqla/__init__.py, fastapi_sqla/_pytest_plugin.py, pyproject.toml, setup.cfg, tests/conftest.py, tests/test_base.py, tests/test_middleware.py, tests/test_open_session.py, tests/test_pagination.py, tests/test_pytest_plugin.py, tests/test_startup.py
* Prepare fastapi-sqla to be compliant with [SQLAlchemy 2.0](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html);
* Run tests with [`SQLALCHEMY_WARN_20`](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-to-2-0-step-two-turn-on-removedin20warnings) environment variable;
* Fix sqla and pytest warnings;
* [DIA-40134]
[DIA-40134]: https://dialoguemd.atlassian.net/browse/DIA-40134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: prepare fastapi-sqla to be compliant with sqlalchemy 2.0 - DIA-40134

fastapi_sqla/_pytest_plugin.py
* Session fixture does not need to open a transaction as there is already one being opened at connection level.
* [DIA-40134]
[DIA-40134]: https://dialoguemd.atlassian.net/browse/DIA-40134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: session fixture does not need to re-open a transaction - DIA-40134

fastapi_sqla/__init__.py, tests/test_middleware.py
Currently, when fastapi-sqla encounters an http error, it will rollback the session, regardless of the error, and log an associated warning. However, this causes a lot of log noise for inconsequential rollbacks (e.g. 404s will also trigger this warning). 
This takes an optimistic approach and checks if a session is dirty (which _could_ but doesn't necessarily indicate that data will be written to DB) before logging the warning, effectively silencing the log when a rollback is expected to be no-op.
See https://app.datadoghq.com/logs?query=app%3Anotepad%20env%3Adev-ca2%20scope%3Acore&agg_m=count&agg_t=count&event=AQAAAYAewq6X7ACj4AAAAABBWUFld3JUdEFBQmxxbk1TTEppcE1nQUk&index=main&from_ts=1649769234000&to_ts=1649783634000&live=false for an example of such log that this would silence.
=> fix: rollback logs warning on clean sessions [DIA-40867]

fastapi_sqla/_pytest_plugin.py, tests/conftest.py, tests/test_startup.py
* The _autoused_ fixtures force a connection to postgres server even if the test being run does not require a connection to postgres;
* The `dont_patch_engine` marker is now set by plugin rather than in conftest;
* Removed unused fixture `sqla_version_tuple`;
* [DM-6561]
* dialoguemd/engage#22
[DM-6561]: https://dialoguemd.atlassian.net/browse/DM-6561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: remove autoused fixtures + set dont_patch_engine marker in plugin - DM-6561

fastapi_sqla/_pytest_plugin.py
* So that the app under test and tests use the same sqla session;
* [DM-6561]
* #54 
* https://github.com/dialoguemd/scribe/pull/1969
* https://github.com/dialoguemd/mattermerde/pull/42
[DM-6561]: https://dialoguemd.atlassian.net/browse/DM-6561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: ensure app under test uses session fixture - DM-6561

poetry.lock, pyproject.toml, tests/pagination/conftest.py, tests/pagination/test_pagination.py
* To decrease the size of #64:
* move pagination tests under a sub-directory;
* update coverage config to fix coverage report of async code:
* https://github.com/nedbat/coveragepy/issues/1216
* https://github.com/nedbat/coveragepy/issues/841#issuecomment-1170098080
* [DIA-46202]
* #64
=> chore: move test_pagination in its own directory - DIA-46202

poetry.lock, pyproject.toml
* `pytest-watch` is not maintained anymore and is not compatible with toml config;
* We were using a branch of the git repo which [caused publishing the package on pypi to fail](https://app.circleci.com/pipelines/github/dialoguemd/fastapi-sqla/571/workflows/4d8ecc21-17c8-41fb-b5e7-a4953cb1d313/jobs/3794?invite=true#step-106-12):
> `HTTP Error 400: Invalid value for requires_dist. Error: Can't have direct dependency: 'pytest-watch @ git+https://github.com/aldencolerain/pytest-watch.git@fix-toml-config ; extra == "tests"'` 
* #66 
* [DIA-46202]
=> chore: remove pytest-watch - DIA-46202

.circleci/config.yml
Update CI `publish` job to use the `python` executor. This should fix [this issue](https://app.circleci.com/pipelines/github/dialoguemd/fastapi-sqla/616/workflows/565cb811-f709-449e-812d-a00110e42cfd/jobs/4414).
* [DIA-50447]
Follow up from https://github.com/dialoguemd/fastapi-sqla/pull/73
[DIA-50447]: https://dialoguemd.atlassian.net/browse/DIA-50447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ci): use python executor for the publish task - DIA-50447

tests/pagination/test_pagination.py, tests/test_pytest_plugin.py
Why?
* Tests marked with `@mark.sqlalchemy("1.3")` will run when sqlalchemy version is `>1.3`, therefore, any `1.3` marker can be removed;
* #76 
* [DIA-51295]
[DIA-51295]: https://dialoguemd.atlassian.net/browse/DIA-51295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: remove duplicate test - DIA-51295

poetry.lock, pyproject.toml
* Fix https://github.com/dialoguemd/fastapi-sqla/security/dependabot/5
=> chore: upgrade pytest to ^7.2.1

fastapi_sqla/asyncio_support.py, fastapi_sqla/aws_aurora_support.py, fastapi_sqla/sqla.py, tests/test_aws_aurora_support.py
Invalidate the database connection when receiving an error caused by trying to execute a write statement on a readonly connection. This will help mitigate issues with AWS Aurora, caused by errors during failover events that can result in the write endpoint pointing to a read instance.
Note that this is an opt-in behaviour, enabled by setting the `fastapi_sqla_aws_aurora_enabled` environment variable to `true`.
* [DIA-51197]
Validated in tests by using a readonly connection ✅ 
[DIA-51197]: https://dialoguemd.atlassian.net/browse/DIA-51197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(aurora): invalidate connection on readonly transaction error - DIA-51197

fastapi_sqla/_pytest_plugin.py, fastapi_sqla/asyncio_support.py, tests/test_middleware.py, tests/test_startup.py
* Table reflection does not work when using async sqlalchemy configuration with sqlalchemy>=2.0.0;
* It was not discovered by tests: I noticed it when trying to upgrade a project to fastapi-sqla=2.8.0 and sqlalchemy>=2.0.0;
* It worked in tests because the fixture async_session depended on sqla_reflection which would run reflection in synchronous mode; Any subsequent call to Base.prepare to do reflection would do nothing as reflection already occurred in test setup;
* Updated `asyncio_support` startup & added a async_sqla_reflection fixture to make async tests fail;
I want to reorganize tests and introduce real integration tests. Doing it in current PR would make it too big IMO;
* [DIA-51295]
* #76
* Closed #81 in favor of current PR.
[DIA-51295]: …
=> fix: table reflection with async db url - DIA-51295

README.md
* Remove links to legacy sqlalchemy doc
* Add @dialoguemd/python-guild as codeowners
* [DIA-53029]
[DIA-53029]: https://dialoguemd.atlassian.net/browse/DIA-53029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: update sqlalchemy links - DIA-53029

fastapi_sqla/__init__.py, fastapi_sqla/asyncio_support.py, fastapi_sqla/models.py, fastapi_sqla/sqla.py
Move models to their own module to have better separation of concerns. This change shouldn't cause any issue since we expect people to include the models from the root module like `from fastapi_sqla import Item`.
* [DIA-61984]
All tests still pass ✅ 
[DIA-61984]: https://dialoguemd.atlassian.net/browse/DIA-61984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: move models to their own modules - DIA-61984

fastapi_sqla/_pytest_plugin.py
Removes dependency on `event_loop` fixture in `async_sqla_connection` pytest plugin fixture, which silences following warning getting logged when running tests on projects which use fastapi-sqla.
```
.venv/lib/python3.11/site-packages/pytest_asyncio/plugin.py:231: 
PytestDeprecationWarning: async_sqla_connection is asynchronous 
and explicitly requests the "event_loop" fixture. Asynchronous 
fixtures and test functions should use "asyncio.get_running_loop()" 
instead.
```
=> fix: pytest plugin event-loop deprecation warning

poetry.lock, pyproject.toml
* Publish failed on: 
```
HTTP Error 400: Invalid value for requires_dist. Error: Can't have direct dependency: 'pytest-watch @ git+https://github.com/styleseat/pytest-watch.git@0342193 
```
* Remove pytest-watch from deps.
* [DIA-65344]
* #114 
[DIA-65344]: https://dialoguemd.atlassian.net/browse/DIA-65344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: publish failed because of pytest-watch - DIA-65344

fastapi_sqla/async_sqla.py, fastapi_sqla/base.py, fastapi_sqla/sqla.py, tests/test_base_setup_middlewares.py, tests/test_setup.py
When using multiple sessions, we've seen sporadic issues coming from the injected middlewares where the response body is missing, causing errors due to a mismatch with the promised `Content-Length`. We've also observed a significant increase in endpoint latency.
Besides, the middleware class we're using, [`BaseHTTPMiddleware`](https://www.starlette.io/middleware/#basehttpmiddleware), is no longer the recommended way of writing middlewares for Starlette. It's known to have functional issues and does not scale well (see [discussion on this FastAPI issue](https://github.com/tiangolo/fastapi/discussions/6985#discussioncomment-8989601), [discussion on this Starlette issue](https://github.com/encode/starlette/issues/1634#issuecomment-1124806406), and [this performance …
=> feat: use pure ASGI middlewares

poetry.lock, pyproject.toml
With the `widen` strategy from Renovate, dependencies are bumped from e.g. `^0.14.0` to `^0.14.0 || ^0.19.0` when a new version is available. That's not what we want, and this is also rejected by PyPI ([example](https://app.circleci.com/pipelines/github/dialoguemd/fastapi-sqla/1086/workflows/aaf2551e-d461-4eaa-9bdd-0f88d54a35b6/jobs/36952?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary)) which prevents the library from being published.
Use ranges for all dependencies, as [that seems to work](https://github.com/dialoguemd/guestlist/pull/302).
* [DIA-70894]
Can only be validated after merging & running Renovate
[DIA-70894]: https://dialoguemd.atlassian.net/browse/DIA-70894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
=> fix(deps): use inequality for all dependencies

.circleci/config.yml
upgrade CI to support python 3.12.5
=> chore(python): upgrade CI to support python 3.12.5 DIA-70641

fastapi_sqla/_pytest_plugin.py, fastapi_sqla/async_sqla.py, fastapi_sqla/base.py, fastapi_sqla/sqla.py, pyproject.toml, tests/test_open_session.py, tests/test_pytest_plugin.py
In the pytest plugin, we patch the `sqla.new_engine` function (and its async equivalent) to return a `Connection` object. This causes issue when running the `startup` function to initialize the session factories, since it expects an engine and uses it to validate that it can connect to the database.
Update the `sqla` and `asyncsqla` module to properly represent that `new_engine` can return either an Engine or a Connection. Update their `startup` function to properly handle both classes.
- Properly type the pytest plugin to ease working on it
- Align `patch_new_engine` and `patch_new_async_engine` fixture implementation to close the transaction on tear down.
- Patch the `new_engine` and `new_async_engine` methods directly in the pytest plugin instead of patching the sqlalchemy function, so …
=> feat(pytest): support startup in tests

.circleci/config.yml
Slack notifications not relevant anymore
Upgrade to latest orbs and remove references to slack one
* [PLAT-98]
[PLAT-98]: https://dialoguemd.atlassian.net/browse/PLAT-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(orbs) decommission slack (PLAT-98)
