- .circleci/config.yml
* CCI matrix like the cool kids.
* [DIA-XXXXX]
* #25 
[Commit Convention]: https://www.notion.so/godialogue/Commit-Convention-84fd9a4c149e48c998d760f1c9176df0
[Code Review guidelines]: https://www.notion.so/godialogue/Code-Review-c5f3fcd185ca49aca73ade497c398fe9
[Draft PR]: https://github.blog/2019-02-14-introducing-draft-pull-requests
> chore: set cci matrix to run tests against sqla 1.3 & 1.4

- README.md
> docs: add response example in readme

- poetry.lock
- pyproject.toml
* Add optional `asyncpg` as extra
> chore: add optional asyncpg dependency to enable asyncio support

- fastapi_sqla/__init__.py
- fastapi_sqla/_pytest_plugin.py
- fastapi_sqla/asyncio_support.py
- pyproject.toml
- tests/conftest.py
- tests/test_asyncio_support.py
- tests/test_middleware.py
* Add `AsyncSession` dependency;
* Add `open_async_session` async context manager;
~- [ ] doc in readme~ in another PR
> feat: add support to use SQLAlchemy async sessions

- README.md
- fastapi_sqla/__init__.py
- fastapi_sqla/_pytest_plugin.py
- fastapi_sqla/asyncio_support.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/test_asyncio_support.py
- tests/test_base.py
- tests/test_db_migration.py
- tests/test_middleware.py
- tests/test_pagination.py
- tests/test_pytest_plugin.py
- tests/test_startup.py
* Document
* `fastapi_sqla.asyncio_support.AsyncSession`
* `fastapi_sqla.asyncio_support.open_session`
* asyncio fixtures
* Fix sqla14 warnings
> docs: document asyncio support

- README.md
- fastapi_sqla/__init__.py
- tests/test_pagination.py
* Allow paginating queries that do not return scalars;
> fix: allow paginating queries that return non scalars - DIA-29942

- README.md
chained style not support yet
[Commit Convention]: https://www.notion.so/godialogue/Commit-Convention-84fd9a4c149e48c998d760f1c9176df0
[Code Review guidelines]: https://www.notion.so/godialogue/Code-Review-c5f3fcd185ca49aca73ade497c398fe9
[Draft PR]: https://github.blog/2019-02-14-introducing-draft-pull-requests
> chore(doc): use valid example in doc

- fastapi_sqla/__init__.py
- fastapi_sqla/_pytest_plugin.py
- setup.cfg
- tests/test_startup.py
> fix: recognize uppercase environment variables - DIA-37058

- README.md
- poetry.lock
- pyproject.toml
* Add development documentation
* Updated deps so what is documented runs 😬 
* [DIA-XXXXX]
> chore: development documentation

- README.md
> chore: add postgres in developer doc

- .circleci/config.yml
- pyproject.toml
> chore: upgrade CCI orbs - DIA-46202

- LICENSE
- README.md
- pyproject.toml
* Update README, LICENCE & package classifiers
* [DIA-46202]
> docs: update README, LICENCE & package classifiers - DIA-46202

- README.md
- fastapi_sqla/__init__.py
- fastapi_sqla/_pytest_plugin.py
- fastapi_sqla/asyncio_support.py
- tests/test_asyncio_support.py
- tests/test_setup.py
- tests/test_startup.py
* `sqlalchemy_url` environment variable accepts async dialect
* #56 
* [DIA-46202]
> feat: sqlalchemy_url accepts async dialect - DIA-46202

- README.md
- fastapi_sqla/__init__.py
- fastapi_sqla/asyncio_support.py
- tests/pagination/conftest.py
- tests/pagination/test_async_pagination.py
Add async pagination;
* #56 
* [DIA-46202]
Blocked by 
* #65 
> feat: add async pagination - DIA-46202

- fastapi_sqla/__init__.py
- tests/test_import.py
* `Collection` & `Item` classes were missing
* [DIA-46292]
* #68 
[DIA-46292]: https://dialoguemd.atlassian.net/browse/DIA-46292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add missing imports - DIA-46202

- .circleci/config.yml
- fastapi_sqla/__init__.py
- fastapi_sqla/asyncio_support.py
- fastapi_sqla/sqla.py
- poetry.lock
- pyproject.toml
- tests/test_startup.py
* Add `py.typed` as required by [PEP-561](https://peps.python.org/pep-0561/)
* Run mypy at CI
* Fix type issues
* [DIA-48104]
[DIA-48104]: https://dialoguemd.atlassian.net/browse/DIA-48104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add type checking support - DIA-48104

- .circleci/config.yml
* run ci with py 3.9 & 3.10
* [DIA-48104]
[DIA-48104]: https://dialoguemd.atlassian.net/browse/DIA-48104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: run ci with py 3.9 & 3.10 - DIA-48104

- .circleci/config.yml
- pyproject.toml
* run ci on python 3.11 as well
* [DIA-48104]
* #71 
[DIA-48104]: https://dialoguemd.atlassian.net/browse/DIA-48104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: run ci on python 3.11 as well - DIA-48104

- .github/renovate.json
To keep up with the dependencies
[DIA-53106]
[DIA-53106]: https://dialoguemd.atlassian.net/browse/DIA-53106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add renovate config - DIA-53106

- README.md
- fastapi_sqla/sqla.py
* Use `DeclarativeBase`
* [DIA-55287]
[DIA-55287]: https://dialoguemd.atlassian.net/browse/DIA-55287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: use DeclarativeBase - DIA-55287

- .circleci/config.yml
- Makefile
Remove gemfury context in favor of new contexts.
Update orbs to latest.
* [DIA-59103]
Ci still works ✅ 
[DIA-59103]: https://dialoguemd.atlassian.net/browse/DIA-59103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(ci): use new contexts - DIA-59103

- fastapi_sqla/sqla.py
* I have introduced dead code in #114 
* Clean the mess!
* #114 
* [DIA-65344]
[DIA-65344]: https://dialoguemd.atlassian.net/browse/DIA-65344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: cleanup useless code - DIA-65344

- .github/CODEOWNERS
* [DIA-70213]
[DIA-71961]: https://dialoguemd.atlassian.net/browse/DIA-71961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DIA-70213]: https://dialoguemd.atlassian.net/browse/DIA-70213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(codeowners): add codeowners
